platform:
  - x64

clone_script:
  - cmd: git clone -q --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
  - cmd: cd %APPVEYOR_BUILD_FOLDER%
  - cmd: git checkout -qf %APPVEYOR_REPO_COMMIT%
  - cmd: git submodule update --init

environment:
  matrix:
    - PY_VERSION: "3.6"
      VC_VERSION: "14"

build_script:
    # This is a small script that takes the PATH variable and transforms its entries
    # into their short-path (DOS-like) counterparts. The new path is written into the file path.txt,
    # from which it is then loaded. This allows to shorten the overall length of the PATH variable,
    # thus avoiding an issue with conda. See also:
    # https://github.com/conda/conda/issues/1923
    # It might be that this will be solved in future conda versions.
  - config\\shorten_path.bat > path.txt
  - set /p PATH=<path.txt
  # we may want to support more python versions in the future
  - if "%PY_VERSION%" == "3.6" set PATH=C:\\Miniconda3-x64\\Scripts;%PATH%
  - if "%PY_VERSION%" == "3.6" conda create -c conda-forge -q --yes -n python python=%PY_VERSION%
  - activate python
  - set CONDA_ACTIVE_ENV=C:\\Miniconda3-x64\\envs\\python
  - set BOOST_INCLUDE=%CONDA_ACTIVE_ENV%\\Library\\include
  - echo "BOOST_ROOT:" 
  - echo "%BOOST_ROOT%"
  - conda install -c conda-forge --yes xtensor-python c-blosc boost bzip2
  - cd %APPVEYOR_BUILD_FOLDER%
  - mkdir build
  - cd build
  - cmake .. -G "Visual Studio %VC_VERSION% Win64" -DCMAKE_PREFIX_PATH="%CONDA_ACTIVE_ENV%" -DWITH_BLOSC=ON -DWITH_ZLIB=ON -DWITH_BZIP2=ON -DWITHIN_TRAVIS=ON -DBOOST_INCLUDE_DIR=%BOOST_INCLUDE%
  - cmake --build .
