platform:
  - x64

clone_script:
  - cmd: git clone -q --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
  - cmd: cd %APPVEYOR_BUILD_FOLDER%
  - cmd: git checkout -qf %APPVEYOR_REPO_COMMIT%
  - cmd: git submodule update --init

environment:
  matrix:
    - PY_VERSION: "3.6"
      VC_VERSION: "14"

build_script:
  - echo %MINICONDA%
  - echo %PATH%
  - conda install python=3.6 xtensor-python boost c-blosc
  - set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%MINICONDA%\\Library;%MINICONDA%\\Library\\bin;%PATH%
  - conda install -c conda-forge --yes xtensor-python c-blosc boost bzip2
  - cd %APPVEYOR_BUILD_FOLDER%
  - mkdir build
  - cd build
  - cmake .. -G "Visual Studio %VC_VERSION% Win64" -DCMAKE_PREFIX_PATH="%PATH%" -DWITH_BLOSC=ON -DWITH_ZLIB=ON -DWITH_BZIP2=ON -DWITHIN_TRAVIS=ON
  - cmake --build .
